name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wokoman/quake3-osp-server:latest,wokoman/quake3-osp-server:${{ steps.date.outputs.date }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Prepare cosign
        shell: bash
        run: |
          'echo "$COSIGN_KEY" > /tmp/cosign.key'
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - name: Sign the pushed image
        run: echo -n "${{ secrets.COSIGN_KEY_PASSPHRASE }}" | cosign sign -key /tmp/cosign.key wokoman/quake3-osp-server:${{steps.date.outputs.date}}
