name: Build and Push Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      # if: ${{ !github.event.pull_request.head.repo.fork }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate docker image tags
      id: metadata
      uses: docker/metadata-action@v4
      with:
        flavor: |
          # Disable latest tag
          latest=false
        images: |
          name=ghcr.io/${{ github.repository_owner }}/q3aosptero
        tags: |
          # Tag with branch name
          type=ref,event=branch
          # Tag with pr-number
          type=ref,event=pr
          # Tag with git tag on release
          type=ref,event=tag
          type=raw,value=release,enable=${{ github.event_name == 'release' }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        # push: ${{ !github.event.pull_request.head.repo.fork }}
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
